package commands

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gtr-manager/internal/goenv"
	"gtr-manager/internal/gomod"
	"gtr-manager/internal/install"
	"gtr-manager/internal/manifest"
	"gtr-manager/internal/semver"
	"gtr-manager/internal/spec"
)

// Init creates gtr.json in the current directory. The -y / --yes flag accepts
// the defaults without prompting (for scripts and CI).
func Init(args []string) error {
	yes := false
	var rest []string
	for _, a := range args {
		switch a {
		case "-y", "--yes":
			yes = true
		default:
			if strings.HasPrefix(a, "-") {
				return fmt.Errorf("unknown flag %s", a)
			}
			rest = append(rest, a)
		}
	}
	if len(rest) > 1 {
		return fmt.Errorf("too many arguments: %s", strings.Join(rest, " "))
	}
	if _, err := os.Stat(manifest.FileName); err == nil {
		return fmt.Errorf("this directory is already initialized as a GTR project")
	}
	wd, err := os.Getwd()
	if err != nil {
		return err
	}
	defaultName := suggestName(filepath.Base(wd))
	// An existing Go project: keep its module path when it is a valid name.
	existing := ""
	if data, err := os.ReadFile("go.mod"); err == nil && !goenv.Generated(".") {
		existing = gomod.Parse(data).Module
		if spec.ValidateName(existing) == nil {
			defaultName = existing
		}
	}
	if len(rest) == 1 && strings.TrimSpace(rest[0]) != "" {
		defaultName = strings.TrimSpace(rest[0])
	}

	q := &asker{r: bufio.NewReader(Stdin), yes: yes}
	m := &manifest.Manifest{
		Name:         q.ask("What is the package name?", defaultName),
		Version:      q.ask("What is the package version?", "1.0.0"),
		Engines:      manifest.Engines{Go: ">=" + defaultGo()},
		Dependencies: map[string]string{},
		Scripts: map[string]string{
			"start": "go run .",
			"build": "go build ./...",
			"test":  "go test ./...",
		},
	}
	if err := spec.ValidateName(m.Name); err != nil {
		return fmt.Errorf("%w (it becomes the import path of the package, ADR-0002)", err)
	}
	if err := CheckName(m.Name); err != nil {
		return err
	}
	if author := q.ask("What is your name?", ""); author != "" {
		m.SetRaw("author", author)
	}
	if homepage := q.ask("What is your website?", ""); homepage != "" {
		m.SetRaw("homepage", homepage)
	}
	if err := manifest.Save(manifest.FileName, m); err != nil {
		return err
	}
	if err := ensureGitignore(); err != nil {
		return err
	}
	fmt.Fprintf(Stdout, "Created %s\n", filepath.Join(wd, manifest.FileName))
	if existing != "" {
		fmt.Fprintln(Stdout, "go.mod was not generated by gtr: run `gtr sync` to import its requirements into gtr.json")
		if existing != m.Name {
			fmt.Fprintf(Stdout, "note: its module path %q differs from the name %q; imports of the project's own packages must use \"%s/...\"\n", existing, m.Name, m.Name)
		}
	}
	return nil
}

// defaultGo is the Go line for engines.go: the version gtr runs us with
// (GTR_GO_VERSION), or the minimum for libraries (ADR-0007).
func defaultGo() string {
	if v, err := semver.Parse(os.Getenv("GTR_GO_VERSION")); err == nil && v.Pre == "" {
		return fmt.Sprintf("%d.%d", v.Major, v.Minor)
	}
	return install.DefaultGo
}

// ensureGitignore adds what gtr generates to .gitignore (ADR-0001, item 7).
func ensureGitignore() error {
	data, err := os.ReadFile(".gitignore")
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	out := string(data)
	for _, line := range []string{install.ModulesDir + "/", "go.mod", "go.work"} {
		if !strings.Contains("\n"+strings.ReplaceAll(out, "\r\n", "\n")+"\n", "\n"+line+"\n") {
			if out != "" && !strings.HasSuffix(out, "\n") {
				out += "\n"
			}
			out += line + "\n"
		}
	}
	if out == string(data) {
		return nil
	}
	return os.WriteFile(".gitignore", []byte(out), 0o644)
}

type asker struct {
	r   *bufio.Reader
	yes bool
	eof bool
}

func (q *asker) ask(question, def string) string {
	if q.yes || q.eof {
		return def
	}
	if def != "" {
		fmt.Fprintf(Stdout, "%s (%s): ", question, def)
	} else {
		fmt.Fprintf(Stdout, "%s: ", question)
	}
	text, err := q.r.ReadString('\n')
	if err != nil { // stdin is closed: use defaults from here on
		q.eof = true
		fmt.Fprintln(Stdout)
	}
	if text = strings.TrimSpace(text); text != "" {
		return text
	}
	return def
}

// suggestName turns a directory name into a valid package name
// ("My Project" → "my-project").
func suggestName(dir string) string {
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(dir) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9' && b.Len() > 0:
			b.WriteRune(r)
			dash = false
		case b.Len() > 0 && !dash:
			b.WriteByte('-')
			dash = true
		}
	}
	name := strings.Trim(b.String(), "-")
	if len(name) < 2 {
		return "app"
	}
	return name
}
