// Package gomod generates go.mod files from gtr.json (ADR-0001).
//
// The project go.mod is canonical — `go mod tidy` leaves it unchanged — and
// carries a header with two hashes, so manual edits are detected:
//
//	// generated by gtr from gtr.json — edit gtr.json or run `gtr sync`
//	// gtr:hash sha256:<hex of the text after the header> sem:<hex of its meaning>
//
// The second hash covers only what matters to the build (module, go
// directive, required versions, replacements), so the go command's own
// bookkeeping — moving a requirement between the direct and "// indirect"
// blocks, adding a toolchain line — is not mistaken for a manual edit.
package gomod

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const (
	headerLine = "// generated by gtr from gtr.json — edit gtr.json or run `gtr sync`"
	hashPrefix = "// gtr:hash sha256:"
	// PackageHeader marks go.mod files gtr writes into package directories.
	PackageHeader = "// generated by gtr — this package is managed by gtr; do not edit"
)

// Require is one module requirement.
type Require struct {
	Path    string
	Version string // with "v": "v0.1.0"
}

// Project describes the project go.mod.
type Project struct {
	Module   string
	Go       string            // go directive, e.g. "1.22"
	Direct   []Require         // first require block
	Indirect []Require         // second block, "// indirect"
	Replace  map[string]string // module → directory ("./gtr_modules/orm")
}

// Render returns the canonical go.mod with the hash header.
func (p Project) Render() []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "module %s\n\ngo %s\n", p.Module, p.Go)
	writeBlock := func(reqs []Require, indirect bool) {
		if len(reqs) == 0 {
			return
		}
		sort.Slice(reqs, func(i, j int) bool { return reqs[i].Path < reqs[j].Path })
		suffix := ""
		if indirect {
			suffix = " // indirect"
		}
		b.WriteString("\n")
		if len(reqs) == 1 {
			fmt.Fprintf(&b, "require %s %s%s\n", reqs[0].Path, reqs[0].Version, suffix)
			return
		}
		b.WriteString("require (\n")
		for _, r := range reqs {
			fmt.Fprintf(&b, "\t%s %s%s\n", r.Path, r.Version, suffix)
		}
		b.WriteString(")\n")
	}
	writeBlock(append([]Require(nil), p.Direct...), false)
	writeBlock(append([]Require(nil), p.Indirect...), true)
	var mods []string
	for m := range p.Replace {
		mods = append(mods, m)
	}
	sort.Strings(mods)
	for _, m := range mods {
		fmt.Fprintf(&b, "\nreplace %s => %s\n", m, p.Replace[m])
	}
	body := b.Bytes()
	sum := sha256.Sum256(body)
	return []byte(fmt.Sprintf("%s\n%s%s sem:%s\n\n%s", headerLine, hashPrefix, hex.EncodeToString(sum[:]), semanticHash(string(body)), body))
}

// Work describes the go.work of a workspace (ADR-0009).
type Work struct {
	Go      string
	Use     []string          // directories: ".", "./core", ...
	Replace map[string]string // module → directory, as in Project
}

// Render returns the canonical go.work with the same hash header as go.mod,
// so Check classifies it too.
func (w Work) Render() []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "go %s\n", w.Go)
	use := append([]string(nil), w.Use...)
	sort.Strings(use)
	if len(use) > 0 {
		b.WriteString("\nuse (\n")
		for _, u := range use {
			fmt.Fprintf(&b, "\t%s\n", autoQuote(u))
		}
		b.WriteString(")\n")
	}
	mods := make([]string, 0, len(w.Replace))
	for m := range w.Replace {
		mods = append(mods, m)
	}
	sort.Strings(mods)
	if len(mods) > 0 {
		b.WriteString("\nreplace (\n")
		for _, m := range mods {
			fmt.Fprintf(&b, "\t%s => %s\n", m, autoQuote(w.Replace[m]))
		}
		b.WriteString(")\n")
	}
	body := b.Bytes()
	sum := sha256.Sum256(body)
	return []byte(fmt.Sprintf("%s\n%s%s sem:%s\n\n%s", headerLine, hashPrefix, hex.EncodeToString(sum[:]), semanticHash(string(body)), body))
}

// autoQuote quotes a path the go.mod/go.work syntax cannot take bare.
func autoQuote(s string) string {
	if s == "" || strings.ContainsAny(s, " \t\"'`(),;{}[]\\") || strings.Contains(s, "//") || strings.Contains(s, "/*") {
		return strconv.Quote(s)
	}
	return s
}

// semanticHash hashes the build-relevant content of a go.mod body:
// module, go directive, requirements and replacements, ignoring comments,
// layout and toolchain lines.
func semanticHash(body string) string {
	var items []string
	inBlock := ""
	for _, line := range strings.Split(strings.ReplaceAll(body, "\r\n", "\n"), "\n") {
		if i := strings.Index(line, "//"); i >= 0 {
			line = line[:i]
		}
		f := strings.Fields(line)
		if len(f) == 0 {
			continue
		}
		if inBlock != "" {
			if f[0] == ")" {
				inBlock = ""
				continue
			}
			items = append(items, inBlock+" "+strings.Join(f, " "))
			continue
		}
		switch {
		case f[0] == "toolchain":
			continue
		case len(f) == 2 && f[1] == "(":
			inBlock = f[0]
		default:
			items = append(items, strings.Join(f, " "))
		}
	}
	sort.Strings(items)
	sum := sha256.Sum256([]byte(strings.Join(items, "\n")))
	return hex.EncodeToString(sum[:])
}

// State is what Check found.
type State int

const (
	Missing    State = iota // no go.mod
	Generated               // generated by gtr and unchanged (or changed only by go's bookkeeping)
	Edited                  // generated by gtr, edited by hand since
	Foreign                 // not generated by gtr
	PackageMod              // written by gtr for a file: package (safe to replace)
)

// Check classifies an existing go.mod.
func Check(path string) (State, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return Missing, nil
	}
	if err != nil {
		return Missing, err
	}
	data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n")) // Git may check out with CRLF
	lines := strings.SplitN(string(data), "\n", 3)
	if len(lines) > 0 && lines[0] == PackageHeader {
		return PackageMod, nil
	}
	if len(lines) < 3 || lines[0] != headerLine || !strings.HasPrefix(lines[1], hashPrefix) {
		return Foreign, nil
	}
	body := strings.TrimPrefix(lines[2], "\n")
	sum := sha256.Sum256([]byte(body))
	textHash, semHash, _ := strings.Cut(strings.TrimPrefix(lines[1], hashPrefix), " sem:")
	switch {
	case textHash == hex.EncodeToString(sum[:]):
		return Generated, nil
	case semHash != "" && semHash == semanticHash(body):
		return Generated, nil
	}
	return Edited, nil
}

// Package renders the go.mod gtr writes into a package directory.
func Package(module, goVersion string, requires []Require) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "%s\n\nmodule %s\n\ngo %s\n", PackageHeader, module, goVersion)
	sort.Slice(requires, func(i, j int) bool { return requires[i].Path < requires[j].Path })
	if len(requires) > 0 {
		b.WriteString("\nrequire (\n")
		for _, r := range requires {
			fmt.Fprintf(&b, "\t%s %s\n", r.Path, r.Version)
		}
		b.WriteString(")\n")
	}
	return b.Bytes()
}

// IsPackageGenerated reports whether a package go.mod was written by gtr.
func IsPackageGenerated(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	return sc.Scan() && strings.TrimRight(sc.Text(), "\r") == PackageHeader
}

var moduleRe = regexp.MustCompile(`(?m)^module\s+("?)([^"\s]+)("?)\s*$`)

// ModulePath returns the module path declared in a go.mod.
func ModulePath(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	m := moduleRe.FindSubmatch(data)
	if m == nil {
		return "", fmt.Errorf("%s: no module line", path)
	}
	return string(m[2]), nil
}

var goVersionRe = regexp.MustCompile(`\d+\.\d+`)

// GoDirective derives the go directive from an engines.go range: the first
// major.minor in it (">=1.22" → "1.22"), or def.
func GoDirective(engines, def string) string {
	if v := goVersionRe.FindString(engines); v != "" {
		return v
	}
	return def
}

// MaxGo returns the higher of two go directives in Go's own ordering, where
// a language version sorts before its pre-releases and releases:
// 1.22 < 1.22rc1 < 1.22.0 < 1.22.1 ("1.22" vs "1.22.0" → "1.22.0").
func MaxGo(a, b string) string {
	if CompareGo(a, b) >= 0 {
		return a
	}
	return b
}

// CompareGo compares Go versions ("1.21", "1.21rc2", "1.21.3").
func CompareGo(a, b string) int {
	pa, pb := parseGo(a), parseGo(b)
	for i := range pa {
		if pa[i] != pb[i] {
			if pa[i] < pb[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}

// parseGo returns major, minor, kind (0 language, 1 beta, 2 rc, 3 release)
// and the beta/rc number or patch.
func parseGo(v string) [4]int {
	var out [4]int
	major, rest, _ := strings.Cut(v, ".")
	out[0] = atoi(major)
	digits := 0
	for digits < len(rest) && rest[digits] >= '0' && rest[digits] <= '9' {
		digits++
	}
	out[1] = atoi(rest[:digits])
	switch suffix := rest[digits:]; {
	case suffix == "":
		out[2] = 0
	case strings.HasPrefix(suffix, "beta"):
		out[2], out[3] = 1, atoi(strings.TrimPrefix(suffix, "beta"))
	case strings.HasPrefix(suffix, "rc"):
		out[2], out[3] = 2, atoi(strings.TrimPrefix(suffix, "rc"))
	case strings.HasPrefix(suffix, "."):
		out[2], out[3] = 3, atoi(suffix[1:])
	}
	return out
}

func atoi(s string) int {
	n := 0
	for _, c := range s {
		if c < '0' || c > '9' {
			break
		}
		n = n*10 + int(c-'0')
	}
	return n
}

// File is a parsed project go.mod (what `gtr sync` needs).
type File struct {
	// Unsupported lists directives gtr.json cannot express ("tool x/y",
	// "exclude m v", "godebug k=v", "ignore ./dir").
	Unsupported []string
	Module      string
	Go          string
	Require     []FileRequire
	Replace     map[string]string // module → target ("./gtr_modules/orm", "../orm.go", "example.com/fork v1.0.0")
}

// ReplaceTarget splits a replace target into its path (unquoted) and
// version ("" for a directory): `"../my lib"` → ("../my lib", "").
func ReplaceTarget(target string) (path, version string) {
	target = strings.TrimSpace(target)
	if strings.HasPrefix(target, `"`) || strings.HasPrefix(target, "`") {
		if q, err := strconv.QuotedPrefix(target); err == nil {
			path, _ = strconv.Unquote(q)
			return path, strings.TrimSpace(target[len(q):])
		}
	}
	path, version, _ = strings.Cut(target, " ")
	return path, strings.TrimSpace(version)
}

// FileRequire is one require line.
type FileRequire struct {
	Path, Version string
	Indirect      bool
}

// Parse reads module, go, require and replace directives of a go.mod.
func Parse(data []byte) File {
	f := File{Replace: map[string]string{}}
	block := ""
	for _, raw := range strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n") {
		line, comment, _ := strings.Cut(raw, "//")
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		indirect := strings.TrimSpace(comment) == "indirect"
		if block != "" {
			if fields[0] == ")" {
				block = ""
				continue
			}
			f.directive(block, fields, indirect)
			continue
		}
		if len(fields) == 2 && fields[1] == "(" {
			block = fields[0]
			continue
		}
		f.directive(fields[0], fields[1:], indirect)
	}
	return f
}

func (f *File) directive(verb string, args []string, indirect bool) {
	switch verb {
	case "module":
		if len(args) > 0 {
			f.Module = strings.Trim(args[0], `"`)
		}
	case "go":
		if len(args) > 0 {
			f.Go = args[0]
		}
	case "require":
		if len(args) >= 2 {
			f.Require = append(f.Require, FileRequire{Path: strings.Trim(args[0], `"`), Version: args[1], Indirect: indirect})
		}
	case "replace":
		// "old [v] => new [v]"
		for i, a := range args {
			if a == "=>" && i > 0 && i+1 < len(args) {
				f.Replace[strings.Trim(args[0], `"`)] = strings.Join(args[i+1:], " ")
			}
		}
	case "tool", "exclude", "godebug", "ignore":
		f.Unsupported = append(f.Unsupported, strings.TrimSpace(verb+" "+strings.Join(args, " ")))
	}
}
