// Package goenv prepares the go command for a gtr project and explains its
// errors in gtr terms (ADR-0001, items 7–8).
//
// The same file is kept in gtr (internal/goenv), which applies it in the go
// shim; keep the copies identical apart from this paragraph.
package goenv

import (
	"bufio"
	"bytes"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
)

// generatedPrefix starts the first line of a go.mod generated by gtr.
const generatedPrefix = "// generated by gtr from gtr.json"

// Generated reports whether dir/go.mod was generated by gtr.
func Generated(dir string) bool {
	return generatedFile(filepath.Join(dir, "go.mod"))
}

// FindWork returns the go.work the go command would use in dir (the first
// one upwards) if gtr generated it (a workspace, ADR-0009) and the module
// of dir is one of its members; otherwise "" (a project nested in a
// workspace without being a member builds on its own).
func FindWork(dir string) string {
	dir, err := filepath.Abs(dir)
	if err != nil {
		return ""
	}
	mod := nearestFile(dir, "go.mod")
	work := nearestFile(dir, "go.work")
	if mod == "" || work == "" || !generatedFile(work) {
		return ""
	}
	modDir := filepath.Dir(mod)
	for _, u := range workUses(work) {
		if !filepath.IsAbs(u) {
			u = filepath.Join(filepath.Dir(work), u)
		}
		if filepath.Clean(u) == modDir {
			return work
		}
	}
	return ""
}

// WorkGo returns the go directive of a go.work ("" if none).
func WorkGo(work string) string {
	data, err := os.ReadFile(work)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n") {
		if f := strings.Fields(line); len(f) == 2 && f[0] == "go" {
			return f[1]
		}
	}
	return ""
}

// workUses lists the use directories of a go.work file.
func workUses(work string) []string {
	data, err := os.ReadFile(work)
	if err != nil {
		return nil
	}
	var out []string
	block := false
	for _, line := range strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n") {
		if i := strings.Index(line, "//"); i >= 0 {
			line = line[:i]
		}
		line = strings.TrimSpace(line)
		switch {
		case block && line == ")":
			block = false
		case block && line != "":
			out = append(out, unquote(line))
		case line == "use (":
			block = true
		case strings.HasPrefix(line, "use "):
			out = append(out, unquote(strings.TrimSpace(strings.TrimPrefix(line, "use "))))
		}
	}
	return out
}

func unquote(s string) string {
	if u, err := strconv.Unquote(s); err == nil {
		return filepath.FromSlash(u)
	}
	return filepath.FromSlash(s)
}

// nearestFile returns the first dir/name upwards from dir, or "".
func nearestFile(dir, name string) string {
	for {
		path := filepath.Join(dir, name)
		if st, err := os.Stat(path); err == nil && !st.IsDir() {
			return path
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func generatedFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	line, _ := bufio.NewReader(f).ReadString('\n')
	return strings.HasPrefix(strings.TrimPrefix(line, "\ufeff"), generatedPrefix)
}

// Env returns base with the settings the go command needs in a gtr project:
// every dependency is a local replacement in gtr_modules, so the network is
// never needed (GOPROXY=off). In a single project go may only do its go.mod
// bookkeeping (-mod=mod, unless GOFLAGS already sets -mod) and go.work files
// outside the project are ignored (GOWORK=off). In a workspace (work is the
// generated go.work) GOWORK points at it and -mod=mod, which go rejects in
// workspace mode, is left out. GOFLAGS set with `go env -w` is kept: an
// environment variable would otherwise hide it.
func Env(base []string, work string) []string {
	env := make([]string, 0, len(base)+3)
	flags, flagsSet, goenvFile := "", false, ""
	for _, kv := range base {
		k, v, _ := strings.Cut(kv, "=")
		switch strings.ToUpper(k) {
		case "GOPROXY", "GOWORK":
			continue
		case "GOFLAGS":
			flags, flagsSet = v, true
			continue
		case "GOENV":
			goenvFile = v
		}
		env = append(env, kv)
	}
	if !flagsSet {
		flags = fileValue(goenvFile, "GOFLAGS")
	}
	if work != "" {
		var kept []string
		for _, f := range strings.Fields(flags) {
			if f != "-mod=mod" {
				kept = append(kept, f)
			}
		}
		return append(env, "GOPROXY=off", "GOWORK="+work, "GOFLAGS="+strings.Join(kept, " "))
	}
	if !strings.Contains(" "+flags, " -mod=") {
		flags = strings.TrimSpace(flags + " -mod=mod")
	}
	return append(env, "GOPROXY=off", "GOWORK=off", "GOFLAGS="+flags)
}

// fileValue reads key from the go env file (GOENV, else
// <user config dir>/go/env), as `go env -w` writes it.
func fileValue(path, key string) string {
	if path == "off" {
		return ""
	}
	if path == "" {
		dir, err := os.UserConfigDir()
		if err != nil {
			return ""
		}
		path = filepath.Join(dir, "go", "env")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n") {
		if k, v, ok := strings.Cut(line, "="); ok && strings.TrimSpace(k) == key {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// RunsPrograms reports whether a go subcommand runs user programs with the
// go command's stderr, so wrapping that stderr would change what they see
// (a terminal becomes a pipe).
func RunsPrograms(args []string) bool {
	for i := 0; i < len(args); i++ {
		a := args[i]
		if a == "-C" { // the only flag go accepts before the subcommand
			i++
			continue
		}
		if strings.HasPrefix(a, "-") {
			continue
		}
		return a == "run" || a == "tool" || a == "generate"
	}
	return false
}

// IsTerminal reports whether f looks like a terminal.
func IsTerminal(f *os.File) bool {
	st, err := f.Stat()
	return err == nil && st.Mode()&os.ModeCharDevice != 0
}

type rule struct {
	re   *regexp.Regexp
	hint func(m []string) string
}

func notInstalled(name string) string {
	if strings.Contains(strings.SplitN(name, "/", 2)[0], ".") {
		return "gtr: " + name + " is not in gtr.json: add its module with `gtr add " + moduleGuess(name) + "`, then run `gtr install`"
	}
	return "gtr: package \"" + name + "\" is not installed: add it with `gtr add github:owner/repo` (or `gtr add file:../path`); if it is already in gtr.json, run `gtr install`"
}

// moduleGuess trims a package path to its likely module on hosts with a
// fixed layout (github.com/o/r/pkg → github.com/o/r, golang.org/x/sync/errgroup
// → golang.org/x/sync), keeping a major version suffix (/v2).
func moduleGuess(pkg string) string {
	parts := strings.Split(pkg, "/")
	n := 0
	switch parts[0] {
	case "github.com", "gitlab.com", "bitbucket.org", "golang.org":
		n = 3
	case "google.golang.org", "gopkg.in":
		n = 2
	}
	if n == 0 || len(parts) <= n {
		return pkg
	}
	if len(parts[n]) > 1 && parts[n][0] == 'v' && strings.Trim(parts[n][1:], "0123456789") == "" {
		n++
	}
	return strings.Join(parts[:n], "/")
}

var rules = []rule{
	{regexp.MustCompile(`package (\S+) is not in std\b`), func(m []string) string { return notInstalled(m[1]) }},
	{regexp.MustCompile(`malformed module path "([^"]+)": missing dot in first path element`), func(m []string) string { return notInstalled(m[1]) }},
	{regexp.MustCompile(`no required module provides package (\S+?);?(\s|$)`), func(m []string) string { return notInstalled(m[1]) }},
	{regexp.MustCompile(`cannot find module providing package (\S+?):? module lookup disabled by GOPROXY=off`), func(m []string) string { return notInstalled(m[1]) }},
	{regexp.MustCompile(`module lookup disabled by GOPROXY=off`), func([]string) string {
		return "gtr: dependencies are installed by gtr, not downloaded by go: use `gtr add <module>` and `gtr install`"
	}},
	{regexp.MustCompile(`ambiguous import: found package (\S+) in multiple modules`), func(m []string) string {
		return "gtr: \"" + m[1] + "\" is provided twice (a gtr package with a standard library or module name?): rename the package in its gtr.json"
	}},
	{regexp.MustCompile(`updates to go\.mod needed|missing go\.sum entry|go\.mod file indicates go [0-9.]+, but maximum version supported|inconsistent vendoring`), func([]string) string {
		return "gtr: go.mod is out of date with gtr.json: run `gtr install` (or `gtr sync` after editing go.mod by hand)"
	}},
}

// Hint returns the gtr hint for one line of go output, or "".
func Hint(line string) string {
	for _, r := range rules {
		if m := r.re.FindStringSubmatch(line); m != nil {
			return r.hint(m)
		}
	}
	return ""
}

// Hints copies lines to w unchanged and, after a line gtr can explain,
// writes the explanation (each one once). Call Close to flush a final line
// without a newline.
type Hints struct {
	w    io.Writer
	mu   sync.Mutex
	buf  []byte
	seen map[string]bool
}

// NewHints wraps w.
func NewHints(w io.Writer) *Hints { return &Hints{w: w, seen: map[string]bool{}} }

func (h *Hints) Write(p []byte) (int, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	h.buf = append(h.buf, p...)
	for {
		i := bytes.IndexByte(h.buf, '\n')
		if i < 0 {
			break
		}
		if err := h.line(h.buf[:i+1]); err != nil {
			return len(p), err
		}
		h.buf = h.buf[i+1:]
	}
	// Do not hold back long partial output (progress lines).
	if len(h.buf) > 4096 {
		_, err := h.w.Write(h.buf)
		h.buf = nil
		return len(p), err
	}
	return len(p), nil
}

func (h *Hints) line(l []byte) error {
	if _, err := h.w.Write(l); err != nil {
		return err
	}
	if hint := Hint(string(l)); hint != "" && !h.seen[hint] {
		h.seen[hint] = true
		_, err := io.WriteString(h.w, hint+"\n")
		return err
	}
	return nil
}

// Unfiltered returns a writer to the same destination that passes output
// through unchanged, serialized with the filtered stream: use it for a
// child's stdout when stdout and stderr share one writer.
func (h *Hints) Unfiltered() io.Writer { return unfiltered{h} }

type unfiltered struct{ h *Hints }

func (u unfiltered) Write(p []byte) (int, error) {
	u.h.mu.Lock()
	defer u.h.mu.Unlock()
	return u.h.w.Write(p)
}

// Close writes what is left.
func (h *Hints) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if len(h.buf) == 0 {
		return nil
	}
	l := h.buf
	h.buf = nil
	if l[len(l)-1] != '\n' {
		l = append(l, '\n')
	}
	return h.line(l)
}
