package goenv

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerated(t *testing.T) {
	dir := t.TempDir()
	if Generated(dir) {
		t.Fatal("no go.mod")
	}
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module x\n"), 0o644)
	if Generated(dir) {
		t.Fatal("foreign go.mod")
	}
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("// generated by gtr from gtr.json — edit gtr.json or run `gtr sync`\r\nmodule x\n"), 0o644)
	if !Generated(dir) {
		t.Fatal("generated go.mod")
	}
}

func TestEnv(t *testing.T) {
	get := func(env []string, k string) (string, int) {
		v, n := "", 0
		for _, kv := range env {
			if strings.HasPrefix(kv, k+"=") {
				v, n = strings.TrimPrefix(kv, k+"="), n+1
			}
		}
		return v, n
	}
	file := filepath.Join(t.TempDir(), "env")
	os.WriteFile(file, []byte("GOFLAGS=-tags=fromfile\nGOPROXY=direct\n"), 0o644)
	if v, _ := get(Env([]string{"GOENV=" + file}, ""), "GOFLAGS"); v != "-tags=fromfile -mod=mod" {
		t.Errorf("GOFLAGS from the go env file: %q", v)
	}
	if v, _ := get(Env([]string{"GOENV=" + file, "GOFLAGS="}, ""), "GOFLAGS"); v != "-mod=mod" {
		t.Errorf("an empty GOFLAGS variable hides the file: %q", v)
	}
	env := Env([]string{"PATH=/bin", "GOPROXY=https://proxy.golang.org", "GOFLAGS=-tags=x", "GOWORK=/w/go.work"}, "")
	for k, want := range map[string]string{"GOPROXY": "off", "GOWORK": "off", "GOFLAGS": "-tags=x -mod=mod", "PATH": "/bin"} {
		if v, n := get(env, k); v != want || n != 1 {
			t.Errorf("%s = %q (%d times), want %q", k, v, n, want)
		}
	}
	if v, _ := get(Env([]string{"GOFLAGS=-mod=vendor"}, ""), "GOFLAGS"); v != "-mod=vendor" {
		t.Errorf("an explicit -mod is kept: %q", v)
	}
	if v, _ := get(Env([]string{"GOENV=off"}, ""), "GOFLAGS"); v != "-mod=mod" {
		t.Errorf("GOFLAGS = %q", v)
	}
}

func TestWorkspace(t *testing.T) {
	root := t.TempDir()
	member := filepath.Join(root, "drivers", "pg")
	os.MkdirAll(member, 0o755)
	if FindWork(member) != "" {
		t.Fatal("no go.work")
	}
	os.WriteFile(filepath.Join(root, "go.work"), []byte("go 1.22\n"), 0o644)
	if FindWork(member) != "" {
		t.Fatal("a go.work gtr did not write")
	}
	work := filepath.Join(root, "go.work")
	os.WriteFile(work, []byte("// generated by gtr from gtr.json — edit gtr.json or run `gtr sync`\ngo 1.23.1\n\nuse (\n\t.\n\t./drivers/pg\n\t\"./my lib\"\n)\n"), 0o644)
	if FindWork(member) != "" {
		t.Fatal("a directory without a go.mod is not a workspace module")
	}
	os.WriteFile(filepath.Join(member, "go.mod"), []byte("module orm-pg\n"), 0o644)
	if FindWork(member) != work || FindWork(filepath.Join(member, "sub")) != work || WorkGo(work) != "1.23.1" {
		t.Fatalf("FindWork = %q", FindWork(member))
	}
	quoted := filepath.Join(root, "my lib")
	os.MkdirAll(quoted, 0o755)
	os.WriteFile(filepath.Join(quoted, "go.mod"), []byte("module mylib\n"), 0o644)
	if FindWork(quoted) != work {
		t.Fatal("quoted use path")
	}
	// A project nested in the workspace without being a member builds alone.
	other := filepath.Join(root, "drivers", "skip")
	os.MkdirAll(other, 0o755)
	os.WriteFile(filepath.Join(other, "go.mod"), []byte("module skip\n"), 0o644)
	if FindWork(other) != "" {
		t.Fatal("not a member")
	}
	env := strings.Join(Env([]string{"GOFLAGS=-mod=mod -tags=x", "GOWORK=off"}, work), "\n")
	if !strings.Contains(env, "GOWORK="+work+"\n") || !strings.Contains(env, "GOFLAGS=-tags=x") || strings.Contains(env, "-mod=mod") || !strings.Contains(env, "GOPROXY=off") {
		t.Fatalf("workspace env:\n%s", env)
	}
}

func TestRunsPrograms(t *testing.T) {
	for args, want := range map[string]bool{"run .": true, "-C dir run .": true, "build ./...": false, "test ./...": false, "generate ./...": true, "": false} {
		if got := RunsPrograms(strings.Fields(args)); got != want {
			t.Errorf("%q: %v", args, got)
		}
	}
}

func TestModuleGuess(t *testing.T) {
	for pkg, want := range map[string]string{
		"golang.org/x/sync/errgroup":            "golang.org/x/sync",
		"github.com/redis/go-redis/v9/internal": "github.com/redis/go-redis/v9",
		"github.com/google/uuid":                "github.com/google/uuid",
		"google.golang.org/grpc/codes":          "google.golang.org/grpc",
		"example.com/a/b":                       "example.com/a/b",
	} {
		if got := moduleGuess(pkg); got != want {
			t.Errorf("%s → %s, want %s", pkg, got, want)
		}
	}
}

func TestHints(t *testing.T) {
	for line, want := range map[string]string{
		`main.go:3:8: package orm is not in std (/usr/local/go/src/orm)`:                                                      `package "orm" is not installed`,
		`go: malformed module path "orm": missing dot in first path element`:                                                  `package "orm" is not installed`,
		`main.go:4:2: no required module provides package github.com/google/uuid/v5/x; to add it:`:                            "gtr add github.com/google/uuid/v5`",
		`main.go:4:2: cannot find module providing package golang.org/x/sync/errgroup: module lookup disabled by GOPROXY=off`: "gtr add golang.org/x/sync`",
		`go: github.com/a/b@v1.0.0: module lookup disabled by GOPROXY=off`:                                                    "installed by gtr, not downloaded",
		`main.go:3:8: ambiguous import: found package errors in multiple modules:`:                                            `"errors" is provided twice`,
		`go: updates to go.mod needed; to update it:`:                                                                         "gtr install",
		`main.go:1:1: undefined: x`: "",
	} {
		if got := Hint(line); want == "" && got != "" || !strings.Contains(got, want) {
			t.Errorf("%q → %q, want %q", line, got, want)
		}
	}
	var out bytes.Buffer
	h := NewHints(&out)
	h.Write([]byte("a.go:1:1: package orm is not in std (/go/src/orm)\nb.go:1:1: package orm is not in std (/go/src/orm)\npartial"))
	h.Write([]byte(" line\nno newline"))
	h.Close()
	lines := strings.Split(strings.TrimSuffix(out.String(), "\n"), "\n")
	if len(lines) != 5 || !strings.HasPrefix(lines[1], "gtr: ") || lines[3] != "partial line" || lines[4] != "no newline" {
		t.Fatalf("%q", lines)
	}
}
